<?php
// Generated by ZF2's ./bin/classmap_generator.php
return array(
  'Payum\PayumModule\Controller\CaptureController'         => __DIR__ . '/src/Payum/PayumModule/Controller/CaptureController.php',
  'Payum\PayumModule\Controller\PayumController'           => __DIR__ . '/src/Payum/PayumModule/Controller/PayumController.php',
  'Payum\PayumModule\Module'                               => __DIR__ . '/src/Payum/PayumModule/Module.php',
  'Payum\PayumModule\Options\PayumOptions'                 => __DIR__ . '/src/Payum/PayumModule/Options/PayumOptions.php',
  'Payum\PayumModule\Options\PayumOptionsFactory'          => __DIR__ . '/src/Payum/PayumModule/Options/PayumOptionsFactory.php',
  'Payum\PayumModule\Registry\RegistryFactory'             => __DIR__ . '/src/Payum/PayumModule/Registry/RegistryFactory.php',
  'Payum\PayumModule\Registry\ServiceLocatorAwareRegistry' => __DIR__ . '/src/Payum/PayumModule/Registry/ServiceLocatorAwareRegistry.php',
  'Payum\PayumModule\Security\HttpRequestVerifier'         => __DIR__ . '/src/Payum/PayumModule/Security/HttpRequestVerifier.php',
  'Payum\PayumModule\Security\HttpRequestVerifierFactory'  => __DIR__ . '/src/Payum/PayumModule/Security/HttpRequestVerifierFactory.php',
  'Payum\PayumModule\Security\TokenStorageFactory'         => __DIR__ . '/src/Payum/PayumModule/Security/TokenStorageFactory.php',
);
